name: Keep Alive Pinger
on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          curl -s https://ollama-fastapi-railway-deployment.fly.dev/ping
          curl -s -X POST https://ollama-fastapi-railway-deployment.fly.dev/warmup
